#!/usr/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
    mod = bld.setup_module_build(bld, 'hashtables_mod', '..')
    mod.source = ['safe_card64table.cpp', 'stringtable.cpp']

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
