#!/usr/bin/env python

import os, Task, Options, Configure, Utils, misc
Configure.autoconfig = 1

# FIXME: Could use bzr python modules, too.
VERSION = os.popen("bzr version-info|grep revno|cut -d' ' -f2").read().strip()
APPNAME = 'vesper'

srcdir = '.'
blddir = '_build_'

source_dirs  = '. lib runtime memory pd schedule boot'
include_dirs = '. lib/klibc lib/bstrlib lib runtime memory pd schedule boot lib/oskit arch/x86 lib/oskit/oskit/x86' #FIXME: archdep
cflags = '-Wall -Wextra -Werror'
cflags += ' -Os' #FIXME: builddep FIXME: -O3 often causes screwups
osflags = '-nostdlib -nostartfiles -nodefaultlibs ' # -fno-builtin
flags = '-fno-stack-protector -fno-leading-underscore'

def set_options(opt):
    opt.add_option("--arch", action="store", default="x86", help="Select architecture to build for.")

def configure(conf):
    # Configure for given platform
    # Configuration name is composed of architecture, cpu, release


    conf.check_tool('gcc g++ nasm misc') # FIXME: gcc detection per-config for x-compile?

    # Set up common environment variables
    conf.env.append_unique('CCFLAGS', cflags + ' ' + flags)
    conf.env.append_unique('CXXFLAGS', cflags + ' -std=gnu++0x ' + flags)
    conf.env.append_unique('CXXDEFINES', ['CONFIG_CPU_IA32_P4'])
    conf.env.append_unique('NASM_FLAGS', '-f elf')

    # Mhm, any better way to define this?
    conf.env['ENV'] = 'x86-release'
    conf.env['TEST_ENV'] = 'x86-tests-release'

    env = conf.env.copy() # Clone environment
    env.set_variant('x86-tests-release') # configure archdep & builddep variant
    conf.set_env_name('x86-tests-release', env)
    env = conf.env.copy() # Clone environment
    env.set_variant('x86-release') # configure archdep & builddep variant
    conf.set_env_name('x86-release', env)

    # Config for running tests
    conf.setenv('x86-tests-release') # Activate the environment
    conf.env['LIB_TEST']      = 'boost_unit_test_framework'
    conf.env.append_unique('CXXFLAGS', '-fexceptions')
    conf.env.append_unique('CXXDEFINES', ['UNIT_TESTS'])

    # Config for building kernel on x86
    conf.setenv('x86-release') # Activate the environment
    conf.env.append_unique('CCFLAGS', osflags)
    conf.env.append_unique('CXXFLAGS', '-fno-rtti -fno-exceptions -std=gnu++0x ' + osflags)
    conf.env.append_unique('CXXDEFINES', ['BOCHS_IO_HACKS']) # debugging hacks for bochs
    conf.env.append_unique('LINKFLAGS', '--gc-sections ' + osflags + flags)

    # Generate config.h (per-environment!)
    conf.define('CONFIG_INLINING', 1)
    conf.define('HEAP_DEBUG', 1)
    conf.write_config_header('config.h')

def build(bld):
    loader = bld.new_task_gen('cxx', 'program')
    loader.source = 'boot/loader.s boot/unpacker.cpp boot/multiboot.cpp lib/default_console.cpp runtime/g++support.cpp runtime/memutils.cpp panic.cpp elf_parser.cpp'
    loader.env = bld.env_of_name(bld.env['ENV']).copy()
    loader.env.append_unique('LINKFLAGS', '-T ../boot/loader.ld -Wl,-Map,bootloader.map')
    loader.includes = include_dirs
    loader.target = 'bootloader'

    initcp = bld.new_task_gen('cxx', 'program')
    initcp.source = 'initcp/initcp.cpp boot/multiboot.cpp lib/default_console.cpp runtime/g++support.cpp runtime/memutils.cpp panic.cpp'
    initcp.env = bld.env_of_name(bld.env['ENV']).copy()
    initcp.env.append_unique('LINKFLAGS', '-T ../initcp/initcp.ld -Wl,-Map,initcomp.map')
    initcp.includes = include_dirs
    initcp.target = 'initcomp'

    #bld.add_subdirs('tests')

def shutdown():
    Utils.exec_command("sh ./update_image.sh")
    #updater = bld.new_task_gen('command-output', outputs='floppy.img', argv=[vesper.target])
    #updater.command = 'sh update_image.sh'
    #updater.command_is_external = True
    #updater.dependencies = [vesper]

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
