#!/usr/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
    vmserver = bld.new_task_gen('cxx', 'program')
    vmserver.source = 'vm_server.cpp'# ../component.lds
    vmserver.env = bld.env_of_name('KERNEL_ENV').copy()
    vmserver.env.append_unique('LINKFLAGS', ['-T', '../vesper/arch-x86/boot_components/component.lds', '-Wl,-Map,vm_server.map'])
    vmserver.includes = '. ../../lib ../../../../lib ../../../../runtime'
    vmserver.target = 'vm_server.comp'
    #vmserver.uselib_local = 'component_runtime'

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
