#!/usr/bin/env python
# -*- coding: utf-8 -*-
from ../module_template import setup_module_build

def build(bld):
    rdom = setup_module_build('root_domain', bld)
    rdom.source = 'entry.cpp root_domain.cpp ../../interfaces/frames_module_interface.cpp ../../interfaces/mmu_module_interface.cpp'.split()
    rdom.includes = '. ../../runtime ../../runtime/stl ../../interfaces ../../kernel/generic ../../kernel/arch/x86 ../../kernel/platform/pc99'
    rdom.uselib_local = 'component_support platform kernel minruntime common'

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
