#!/usr/bin/env python
# -*- coding: utf-8 -*-
from waflib import Options
import os

def build(bld):
    arch = Options.options.arch
    platform = Options.options.platform

    complib = bld.stlib(
        source = 'module-entry.cpp heap_new.cpp',
        target = 'component_support',
        env = bld.all_envs['KERNEL_ENV'].derive()
    )
    complib.gen_incpaths('../')

    bld.recurse('tcb')
    bld.recurse('heap_mod')
    bld.recurse('context_mod')
    bld.recurse('hashtables_mod')
    bld.recurse('stretch_table_mod')
    bld.recurse('exceptions_mod')
    # bld.recurse('pcibus')
