#!/usr/bin/env python
# -*- coding: utf-8 -*-
import Options

def build(bld):
    arch = Options.options.arch
    platform = Options.options.platform

    complib = bld.new_task_gen('cxx', 'staticlib')
    complib.source = 'module-entry.cpp heap_new.cpp'
    complib.env = bld.env_of_name('KERNEL_ENV').copy()
    complib.includes = ['.', '../runtime', '../runtime/stl', '../interfaces', '../kernel/generic', '../kernel/arch/'+arch, '../kernel/arch/shared', '../kernel/platform/'+platform, '../kernel/platform/shared']
    complib.target = 'component_support'

    bld.add_subdirs('platform/shared')
    bld.add_subdirs('platform/'+platform+'/mmu_mod')
    bld.add_subdirs('root_domain')
    bld.add_subdirs('frames_mod')
    bld.add_subdirs('heap_mod')
    bld.add_subdirs('stretch_allocator_mod')
    bld.add_subdirs('stretch_table_mod')
    bld.add_subdirs('stretch_driver_mod')
    bld.add_subdirs('exceptions_mod')
    bld.add_subdirs('hashtables_mod')
    bld.add_subdirs('typesystem_mod')

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
