#!/usr/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
    idisp = bld.new_task_gen('cxx', 'program')
    idisp.source = 'scheduler.cpp'# ../component.lds
    idisp.env = bld.env_of_name('KERNEL_ENV').copy()
    idisp.env.append_unique('LINKFLAGS', ['-Wl,-defsym,U_CODE_START=0x220000','-T', '../vesper/arch-x86/boot_components/component.lds', '-Wl,-Map,scheduler.map'])
    idisp.includes = '. ../../lib ../../../../lib ../../../../runtime'
    idisp.target = 'scheduler.comp'
    #idisp.uselib_local = 'component_runtime'

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
