#!/usr/bin/env python
# -*- coding: utf-8 -*-
import Options

def build(bld):
    arch = Options.options.arch
    platform = Options.options.platform
    libplatform = bld.new_task_gen('cxx', 'staticlib')
    libplatform.source = 'default_console.cpp ../../../kernel/arch/hosted/panic.cpp'.split()
    libplatform.env = bld.env_of_name('KERNEL_ENV').copy()
    # STL is included from the host system!
    libplatform.includes = ['.', '../../../runtime', '../../../interfaces', '../../../kernel/generic', '../../../kernel/arch/'+arch, '../../../kernel/arch/shared', '../../../kernel/platform/'+platform, '../../../kernel/platform/shared'] #libplatform.env['INCLUDE_DIRS']
    libplatform.target = 'platform'

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
