#!/usr/bin/env python
# -*- coding: utf-8 -*-
import Options, os

# Convert INCLUDE_DIRS into includes variable with a given prefix, work around absolute include paths if given.
# @conf
def gen_incpaths(bld, prefix):
    incs = []
    for x in bld.env.INCLUDE_DIRS:
        if os.path.isabs(x):
            incs.append(x)
        else:
            incs.append(prefix+x)
    bld.includes = incs


def build(bld):
    arch = Options.options.arch

    platform = bld.stlib(
        source = map(lambda d: d, 'multiboot.cpp default_console.cpp'.split()),
        target = 'platform',
        env = bld.all_envs['KERNEL_ENV'].derive()
    )
    gen_incpaths(platform, '../../../')

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
