#!/usr/bin/env python
# -*- coding: utf-8 -*-
# import Options

def build(bld):
    platform = bld.stlib(
        source = map(lambda d: d, 'multiboot.cpp default_console.cpp'.split()),
        target = 'platform',
        env = bld.all_envs['KERNEL_ENV'].derive()
    )
    platform.gen_incpaths('../../../')

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
