#!/usr/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
    mod = bld.setup_module_build('pcibus_mod', '..', 'pcibus_mod.cpp ../../devices/network/ne2000_pci/ne2k.cpp')

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
