#!/usr/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
    mmu_mod = bld.new_task_gen('cxx', 'program')
    mmu_mod.name = 'mmu_mod.comp'
    mmu_mod.source = 'mmu_mod.cpp'
    mmu_mod.env = bld.env_of_name('KERNEL_ENV').copy()
    mmu_mod.env.append_unique('LINKFLAGS', ['-r']); # Components are relocatable
    mmu_mod.env.append_unique('LINKFLAGS', ['-T', '../modules/component.lds', '-Wl,-Map,mmu_mod.map'])
    mmu_mod.includes = '. ../../runtime ../../runtime/stl ../../interfaces ../../kernel/generic ../../kernel/arch/x86 ../../kernel/platform/pc99'
    mmu_mod.uselib_local = 'component_support platform kernel minruntime common'
    mmu_mod.target = 'mmu_mod.comp'

    bld.new_task_gen(
        source = 'mmu_mod.comp',
        rule = 'nm -u ${SRC[0].abspath(env)}',
        name = 'mmu_mod module nm undef check',
        after = 'cxx_link'
    )

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
