#!/usr/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
    mod = bld.setup_module_build('typesystem_mod', '../..', 'typesystem_mod.cpp interface.cpp operation.cpp enum_rec_choice_exception.cpp')
