#!/usr/bin/env python
# -*- coding: utf-8 -*-
from waflib import Options
import os

def build(bld):
    arch = Options.options.arch
    platform = Options.options.platform

    bld.recurse('platform/shared')
    bld.recurse('platform/'+platform+'/mmu_mod')
    bld.recurse('root_domain')
    bld.recurse('frames_mod')
    bld.recurse('stretch_allocator_mod')
    bld.recurse('stretch_driver_mod')
    bld.recurse('typesystem_mod')
    # bld.recurse('gatekeeper_mod')
