#!/usr/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
    mod = bld.setup_module_build('mmu_mod', '../../..', 'mmu_mod.cpp')

# kate: indent-width 4; replace-tabs on;
# vim: set et sw=4 ts=4 sts=4 cino=(4 :
