#!/bin/sh

name="$1"

mkdir modules/$name
cat modules/$name/wscript <<EOF
#!/usr/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
    mod = bld.setup_module_build(bld, 'root_domain')
    mod.source = 'entry.cpp root_domain.cpp'.split()
    mod.idl_source = 'all_idl'
EOF

